### ISSUE TITLE
Setting Textarea initial state

### ISSUE THREAD

**Issue by laffan** [JMBeresford/r3f-form#17]
I'm looking for a way to set `<Textarea>`'s initial value, the way you might in HTML.  Just getting at the node itself seems to require `useCallback` (as suggested in [the react docs](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node)) but this breaks the connection to the inner elements somehow, despite returning the root `<textarea>` element. I've tried hunting through `src/components/Textarea/Text.tsx` but don't see any obvious way to implement it on my own.  

Current attempt :
```jsx
...
  const callbackRef = useCallback(node => {
    if (node !== null) {
      console.log(node); // returns <textarea> html
      node.innerHTML = "Initial Content" // No luck.
    }
  }, []);

  return (
    <Textarea ref={callbackRef}  />
  );
...
``` 

If you have any suggestions they would be most welcome.  Thank you!

**Comment by laffan** [comment]
Never mind! For anyone happening upon this in the future, [the link](https://github.com/protectwise/troika/tree/master/packages/troika-3d-text) @JMBeresford provides will reveal the following: 

```jsx
<Textarea ref={ref} textProps={{text: "Initial Content"}}  />
```

(Update, 2 hrs later : Unfortunately, what this doesn't do is allow the user to edit that initial text. When new text is entered the onChange event clears out the entire field and starts fresh. ( Initial testing with some kind of [event trigger hack](https://codesandbox.io/embed/trigger-example-s68im?fontsize=14) has proven unsuccessful. ) I'll check back tomorrow if this is actually a bug or just sleeplessness on my end.)   @JMBeresford  any help would be very welcome!

**Comment by JMBeresford** [comment]
Yes, though this is not necessarily a bug it is not a currently supported feature. Though the current API rewrite ( loosely described in #14 ) will incidentally add this feature.

I'll likely get that done and merged this week at some point.

**Comment by laffan** [comment]
Fantastic. Thanks for the update!

**Comment by JMBeresford** [comment]
Going to re-open this until the refactor is merged. This way you know when it's done, and there is clear trail to what resolved this issue 😃

**Comment by JMBeresford** [comment]
@laffan defaultValue prop should get you what you need now

**Comment by laffan** [comment]
@JMBeresford  Thank you so much! This looks like solid progress on all fronts.

Strangely, I'm still encountering strange behavior with the defaultValue prop in controlled forms. There seem to be two issues, possibly interrelated.

1. The text doesn't appear until the user starts typing.
2. Once visible, the carat still starts at the beginning of the document, rather than the end, where you'd expect it in an HTML text field.

You can see a demo of the behavior here : https://codesandbox.io/s/r3f-form-textarea-issue-v5qnz0?file=/src/App.js

Anyways, thank you again for putting so much time in to this. That I'm typing all this out less than an hr after your 2.0 release should be some indication of how excited I am to use this in upcoming projects :-)

**Comment by JMBeresford** [comment]
@laffan Yes, because of course I only added that support to `<Input />` 🤦🏻 

Anyways, 2.0.1 seems to be working -- thank you for the speedy feedback!
